---
title: "analisis de vias cd4s 2024"
author: "Linda Kempis"
date: "2024-05-16"
output: html_document
---

######  Analisis de vias sobrereprentadas con la tabala de listas de genes  #####
#Programa: Anotacion de datos de Expresion diferencial con Clusterprofiler
#Lugar: My home
#Desarrolladora: Linda Aimara Kempis Calanis


```{r}
####Librerias necesarias####
library(clusterProfiler)
library(org.Hs.eg.db)
library(ggplot2)
packageDescription("clusterProfiler")

```



```{r}
#1. Debemos elegir la direccion de los archivos
#2 Leer las tablas necesarias para las comparaciones neonatos vs adultos
res_df1 <-read.table("Neo_vs_Adultos_DiffExp_edgeR.txt")
dim(res_df1)
padj.cutoff <-0.05
lfc.cutoff<- 1


#3 Seleccionar el entrezgeid de los genes up and down de las tablas

GDE_Neo <- res_df1 %>% filter(FDR<= padj.cutoff & logFC <= -lfc.cutoff)
dim(GDE_Neo)
View(GDE_Neo)
GDE_Adul <- res_df1 %>% filter(FDR<= padj.cutoff & logFC >= lfc.cutoff)
dim(GDE_Adul)

gene_adul <- GDE_Adul$gene
length(gene_adul)
gene_neo  <- GDE_Neo$gene
View(gene_neo)


##4 convertir los genes a entrezgenid
genes_neo_entrez = bitr(gene_neo, fromType = "SYMBOL", toType = "ENTREZID", OrgDb ="org.Hs.eg.db" )
View(genes_neo_entrez)
genes_adu_entrez = bitr(gene_adul, fromType = "SYMBOL", toType = "ENTREZID", OrgDb ="org.Hs.eg.db" )
View(genes_adu_entrez)

col_genes_neo_entrez <- genes_neo_entrez$ENTREZID
col_genes_adu_entrez <- genes_adu_entrez$ENTREZID
```


```{r}
kk <- enrichGO(gene         = col_genes_neo_entrez,
                 OrgDb         = org.Hs.eg.db,
                ont           = "BP",
                 pvalueCutoff = 0.05,
                 qvalueCutoff= 0.1)
```

```{r}

```


```{r}
via <- dotplot(kk, showCategory = 20, font.size=10.5) +ggtitle("Enrichment Analysis")
via
```

## Crear una lista 
```{r}
lista_NeovsAdu <- list("Neonatos" = col_genes_neo_entrez, "Adultos" = col_genes_adu_entrez)
```

```{r}
clusters_GO <- compareCluster(geneCluster = lista_NeovsAdu, fun = enrichGO, OrgDb  = "org.Hs.eg.db",ont = "BP", pvalueCutoff = 0.05,qvalueCutoff = 0.1)
View(clusters_GO)
class(clusters_GO)
```

# Guardar tabla
```{r}
write.table(clusters_GO, file = 'clusterprofiler_GO.txt', sep="\t", col.names =T)
```



```{r}
clusters <- compareCluster(geneCluster = lista_NeovsAdu, fun = enrichKEGG, organism = "hsa", pvalueCutoff = 0.05,qvalueCutoff= 0.1)
View(clusters)
class(clusters)

write.table(clusters, file = 'clusterprofiler.txt', sep="\t", col.names =T)
```
## Dotplot procesos BP

```{r}
vias_GO <- dotplot(clusters_GO, showCategory = 20, font.size=9) + ggtitle("Enrichment Analysis")
vias_GO
```


##Dotplot de vias
```{r}
vias <- dotplot(clusters, showCategory = 20, font.size=10.5) +ggtitle("Enrichment Analysis")
vias
```

